### ISSUE TITLE
can't import Amy

### ISSUE THREAD

**Issue by steeley** [shorepine/amy#181]
I have installed the library as per the readme instructions, and I can use 
`make ./amy-example`
to compile and hear sound.

I can't run Amy in python-  import Amy just says no module found. I'm on Intel MacBook osx Ventura 13.6.9, python 3.12

output from pip install:
` pip install . .
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/qt_material-2.14-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Processing /Users/ian/amyDSP/src
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: libamy
  Building wheel for libamy (setup.py) ... done
  Created wheel for libamy: filename=libamy-0.0.0-cp312-cp312-macosx_10_9_universal2.whl size=1901127 sha256=94dd752bdbb88a88cb047a65b1464f3e76232cb2afdb8e9c253f6d7a6860eae2
  Stored in directory: /private/var/folders/w3/rzctjzp952nb7qxljdy7rw600000gn/T/pip-ephem-wheel-cache-088_l58h/wheels/4b/5a/24/1833746e535b7db6337de9b5c3bbbf96c80a511c86cf1ea634
Successfully built libamy
Installing collected packages: libamy
Successfully installed libamy-0.0.0`

**Comment by bwhitman** [comment]
Try make test

If that works (you see test results) try running python3 and then importing libamy

**Comment by dpwe** [comment]
You need to start the audio:

$ python3
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0
(clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import amy
>>> amy.live()
>>> amy.drums()

If you have anything more than the default speakers attached, you might need:
>>> amy.live(audio_device=1)
or some other number.

Thonny IIUC is a front-end for micropython running on device, so its
available libraries are unrelated to whatever you can get with python
running on your host.  It should be possible to get an amy library
available on your target micropython device, but we haven't tried
that.  Instead, Tulip builds as a complete Micropython environment
including Amy baked-in.

  DAn.

**Comment by steeley** [comment]
ok sort off got it working from terminal.
I use Thonny with ESP etc and desktop Python stuff and it works well. Shame I can't get it to work with Amy.
yes, aware of Tulip.

my goal is to get a DSP/sound/synth DSP lib that works  easily on both desktop and embedded stuff.

thanks

**Comment by bwhitman** [comment]
We have plans to port AMY and the parts of tulip that interact with AMY to pure micropython for things like thonny. But for now you'll have to DIY or use tulip itself. https://github.com/shorepine/tulipcc/issues/309 

Glad you got python AMY going on desktop!

**Comment by dpwe** [comment]
In my experience with Thonny running on an RP2040, installing a library involved dragging an mpy file onto the device when mounted as a mass storage device, then rebooting, and somehow the micropython on the target device was then able to find it (IIRC).

Figuring out how to compile Amy into such an mpy object file should be pretty easy.  But to make it run on some arbitrary target device is more than just linking python functions: To run Amy, there needs to be an audio kernel running all the time as a separate thread, and that kernel needs to know where the audio interface is and how to send samples to it.  That sounds like a lot more work, I'm not sure how you'd even get a separate thread running under Thonny/stock MicroPython.

**Comment by steeley** [comment]
got Thonny running with Amy and desktop Python3 - had to reset some paths. I'm just using the desktop python with amy to generate some automated tones and signals to auto test some audio hardware.

thanks again to all for the suggestions
